// Copyright 2004, 2005 Macromedia, Inc. All rights reserved.
MM.HELP_mnuCFUsing = "CF_Using:index.htm";
MM.HELP_mnuDWHelp = "DW_Using:index.htm";
MM.HELP_mnuDWExtending = "DW_Extending:index.htm";
MM.HELP_mnuDWAPI = "DW_API:index.htm";
MM.HELP_mnuDWGettingStarted = "DW_Using:part1_ge.htm"; // Getting Started help menu entry
MM.HELP_mnuDWUsing = "DW_Using:part0_dr.htm"; // Using DW Menu ID
MM.HELP_mnuDWWhatsNew = "DW_Using:01_welc2.htm"; // Whats new menu entry
MM.HELP_customizeFavorites = "DW_Using:02_exp59.htm"; 
MM.HELP_objAcronym = "DW_Using:02_exp61.htm"; 
MM.HELP_objAbbreviation = "DW_Using:02_exp61.htm"; 
MM.HELP_cmdKeyboardShortcuts = "DW_Using:02_exp63.htm"; 
MM.HELP_cmdCleanUpWordHTML = "DW_Using:04_doc16.htm"; 
MM.HELP_cmdImportWordHTML = "DW_Using:04_doc16.htm"; 
MM.HELP_recentlyModifiedMC = "DW_Using:05_sit66.htm"; 
MM.HELP_cmdDesignNotes = "DW_Using:05_sit72.htm"; 
MM.HELP_recentlyModifiedReport = "DW_Using:05_sit75.htm"; 
MM.HELP_objDiv = "DW_Using:08_css48.htm"; 
MM.HELP_mnuEditGuides = "DW_Using:08_css56.htm"; // Guides dialog
MM.HELP_mnuExplodedModeIntro = "DW_Using:09_tab11.htm"; 
MM.HELP_objTable = "DW_Using:09_tab28.htm"; 
MM.HELP_objTabularData = "DW_Using:09_tab29.htm"; // stored in Commands
MM.HELP_cmdFormatTable = "DW_Using:09_tab32.htm"; 
MM.HELP_cmdSortTable = "DW_Using:09_tab35.htm"; 
MM.HELP_cmdExportTable = "DW_Using:09_tab36.htm"; 
MM.HELP_mnuLayoutViewIntro = "DW_Using:10_layo2.htm"; 
MM.HELP_objFrameAccessOptions = "DW_Using:11_fra23.htm"; // frames accessibility dialog
MM.HELP_inspEditableContent = "DW_Using:12_tem28.htm"; // editable region PI
MM.HELP_inspOptionalContent = "DW_Using:12_tem35.htm"; 
MM.HELP_editableTagAttributes = "DW_Using:12_tem37.htm"; 
MM.HELP_templateProperties = "DW_Using:12_tem52.htm"; 
MM.HELP_insertEditableRegion = "DW_Using:12_tem56.htm"; 
MM.HELP_insertRepeatingContent = "DW_Using:12_tem57.htm"; 
MM.HELP_objRepeatingTable = "DW_Using:12_tem58.htm"; 
MM.HELP_insertOptionalContent = "DW_Using:12_tem59.htm"; 
MM.HELP_orphanedTemplateContent = "DW_Using:12_tem60.htm"; 
MM.HELP_editableTagAttributes = "DW_Using:12_tem61.htm"; 
MM.HELP_extractTemplateXML = "DW_Using:12_tem65.htm"; 
MM.HELP_templateDescription = "DW_Using:12_tem66.htm"; // Template Description dialog
MM.HELP_cmdSetColorScheme = "DW_Using:13_pag14.htm"; 
MM.HELP_objDate = "DW_Using:14_tex30.htm"; // stored in Commands
MM.HELP_inspDate = "DW_Using:14_tex30.htm"; 
MM.HELP_objInsertEntity = "DW_Using:14_tex31.htm"; // stored in Commands
MM.HELP_cmdDesignTimeCSS = "DW_Using:14_tex43.htm"; 
MM.HELP_objDropOffice = "DW_Using:14_tex66.htm"; 
MM.HELP_objImageAccessOptions = "DW_Using:15_ima17.htm"; //image accessibility dialog
MM.HELP_objImgPlaceholder = "DW_Using:15_ima19.htm"; 
MM.HELP_objRolloverImage = "DW_Using:15_ima22.htm"; // stored in Commands
MM.HELP_objAnchor = "DW_Using:16_lin27.htm"; 
MM.HELP_objHyperlink = "DW_Using:16_lin28.htm"; // insert hyperlink
MM.HELP_objEMailLink = "DW_Using:16_lin29.htm"; 
MM.HELP_objJumpMenu = "DW_Using:16_lin31.htm"; // stored in Commands
MM.HELP_objNavBar = "DW_Using:16_lin32.htm"; // stored in Commands
MM.HELP_cmdModifyNavBar = "DW_Using:16_lin32.htm"; 
MM.HELP_objFireworksHTML = "DW_Using:17_oth11.htm"; 
MM.HELP_cmdCreateWebPhotoAlbum = "DW_Using:17_oth14.htm"; 
MM.HELP_objFlashText = "DW_Using:18_med14.htm"; 
MM.HELP_objFlashPaper = "DW_Using:18_med19.htm"; 
MM.HELP_FlashVideo_PI = "DW_Using:18_med24.htm"; 
MM.HELP_objFlashVideo = "DW_Using:18_med39.htm"; 
MM.HELP_objFlashAccessOptions = "DW_Using:18_med44.htm"; //flash button and flash text dialog
MM.HELP_objObjectAccessOptionsdialog = "DW_Using:18_med44.htm"; //generator, flash, activex, shockwave attributes dialog
MM.HELP_objFlashButton = "DW_Using:18_med45.htm"; 
MM.HELP_behCallJavaScript = "DW_Using:19_jsb11.htm"; 
MM.HELP_behChangeProperty = "DW_Using:19_jsb12.htm"; 
MM.HELP_behCheckBrowser = "DW_Using:19_jsb13.htm"; 
MM.HELP_behCheckPlugin = "DW_Using:19_jsb14.htm"; 
MM.HELP_behControlShockwave = "DW_Using:19_jsb15.htm"; 
MM.HELP_behDragLayer = "DW_Using:19_jsb16.htm"; 
MM.HELP_behGoToURL = "DW_Using:19_jsb18.htm"; 
MM.HELP_behJumpMenu = "DW_Using:19_jsb19.htm"; 
MM.HELP_behJumpMenuGo = "DW_Using:19_jsb20.htm"; 
MM.HELP_behOpenBrowserWindow = "DW_Using:19_jsb21.htm"; 
MM.HELP_behPlaySound = "DW_Using:19_jsb22.htm"; 
MM.HELP_behPopupMessage = "DW_Using:19_jsb23.htm"; 
MM.HELP_behPreloadImages = "DW_Using:19_jsb24.htm"; 
MM.HELP_behSetNavBarImage = "DW_Using:19_jsb25.htm"; 
MM.HELP_behSetTextOfFrame = "DW_Using:19_jsb26.htm"; // stored in sub-folder Set Text
MM.HELP_behSetTextOfLayer = "DW_Using:19_jsb27.htm"; // stored in sub-folder Set Text
MM.HELP_behSetTextOfStatusBar = "DW_Using:19_jsb28.htm"; // stored in sub-folder Set Text
MM.HELP_behSetTextOfTextField = "DW_Using:19_jsb29.htm"; // stored in sub-folder Set Text
MM.HELP_behShowHideLayers = "DW_Using:19_jsb30.htm"; 
MM.HELP_behShowPopupMenu = "DW_Using:19_jsb31.htm"; 
MM.HELP_behHidePopupMenu = "DW_Using:19_jsb31.htm"; 
MM.HELP_behSwapImage = "DW_Using:19_jsb37.htm"; 
MM.HELP_behSwapImageRestore = "DW_Using:19_jsb38.htm"; 
MM.HELP_behValidateForm = "DW_Using:19_jsb39.htm"; 
MM.HELP_FW8PopupMenus = "DW_Using:19_jsb42.htm"; // Show popup menu help topic
MM.HELP_dtdImport = "DW_Using:21_cod20.htm"; 
MM.HELP_aspnetImportSelected = "DW_Using:21_cod21.htm"; 
MM.HELP_newTags = "DW_Using:21_cod37.htm"; 
MM.HELP_newAttributes = "DW_Using:21_cod38.htm"; 
MM.HELP_tiImportTLDFile = "DW_Using:21_cod39.htm"; 
MM.HELP_cmdtiImportWebXML = "DW_Using:21_cod40.htm"; 
MM.HELP_tiImportTLDFolder = "DW_Using:21_cod41.htm"; 
MM.HELP_objComment = "DW_Using:22_cod33.htm"; 
MM.HELP_cmdCleanUpHTML = "DW_Using:23_codi9.htm"; 
MM.HELP_objScript = "DW_Using:24_cod21.htm"; 
MM.HELP_inspSsiCommon = "DW_Using:24_cod24.htm"; 
MM.HELP_objMeta = "DW_Using:24_cod27.htm"; 
MM.HELP_inspMeta = "DW_Using:24_cod27.htm"; 
MM.HELP_inspTitle = "DW_Using:24_cod28.htm"; 
MM.HELP_objKeywords = "DW_Using:24_cod29.htm"; 
MM.HELP_inspKeywords = "DW_Using:24_cod29.htm"; 
MM.HELP_objDescription = "DW_Using:24_cod30.htm"; 
MM.HELP_inspDescription = "DW_Using:24_cod30.htm"; 
MM.HELP_objRefresh = "DW_Using:24_cod31.htm"; 
MM.HELP_inspRefresh = "DW_Using:24_cod31.htm"; 
MM.HELP_objBase = "DW_Using:24_cod32.htm"; 
MM.HELP_inspBase = "DW_Using:24_cod32.htm"; 
MM.HELP_objLink = "DW_Using:24_cod33.htm"; 
MM.HELP_inspLink = "DW_Using:24_cod33.htm"; 
MM.HELP_inspGeneric = "DW_Using:24_cod34.htm"; // generic PI
MM.HELP_DSsettingDB2 = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingInformix = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingMSAccess = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingMSAccessUnicode = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingMSSQL = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingMySQL = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingODBC = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingOracle = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingOther = "DW_Using:26_conn7.htm"; 
MM.HELP_DSsettingSybase = "DW_Using:26_conn7.htm"; 
MM.HELP_connASPNETOleDb = "DW_Using:27_conn9.htm"; 
MM.HELP_connASPNETOleDbTemplate = "DW_Using:27_con10.htm"; 
MM.HELP_connASPNETSqlServer = "DW_Using:27_con11.htm"; 
MM.HELP_connASPDSN = "DW_Using:28_con14.htm"; 
MM.HELP_cmdSelectDSNList = "DW_Using:28_con15.htm"; 
MM.HELP_connASPConnString = "DW_Using:28_con16.htm"; 
MM.HELP_connJSP = "DW_Using:29_conn9.htm"; 
MM.HELP_connPHP = "DW_Using:30_conn5.htm"; // MySQL Connection dialog
MM.HELP_cmdSelectPHPDSNList = "DW_Using:30_conn6.htm"; 
MM.HELP_compJavaBeans = "DW_Using:32_dyn15.htm"; // JavaBeans view of Components panel
MM.HELP_ssURLVariable = "DW_Using:35_con15.htm"; 
MM.HELP_ssFormVariable = "DW_Using:35_con16.htm"; 
MM.HELP_dataSourceNameVariable = "DW_Using:35_con19.htm"; // Data Source Name Variable
MM.HELP_ssCookieVariable = "DW_Using:35_con20.htm"; 
MM.HELP_ssServerVariable = "DW_Using:35_con20.htm"; 
MM.HELP_ssEnvironmentVariable = "DW_Using:35_con20.htm"; 
MM.HELP_ssDynamicBinding = "DW_Using:35_con29.htm"; 
MM.HELP_ssSimpleRecordset = "DW_Using:35_con30.htm"; 
MM.HELP_ssCFSimpleRecordset = "DW_Using:35_con31.htm"; // Simple Recordset ColdFusion
MM.HELP_cmdcfDataSourceLogin = "DW_Using:35_con31.htm"; // Data Source Login
MM.HELP_sbASPNetSimpleRecordset = "DW_Using:35_con32.htm"; 
MM.HELP_ssAdvancedRecordset = "DW_Using:35_con33.htm"; 
MM.HELP_sbASPNetAdvRecordset = "DW_Using:35_con34.htm"; 
MM.HELP_ssCFAdvancedRecordset = "DW_Using:35_con35.htm"; 
MM.HELP_ssRequestVariable = "DW_Using:35_con36.htm"; 
MM.HELP_cmdASPNetAddParam = "DW_Using:35_con36.htm"; 
MM.HELP_cmdCFAddParam = "DW_Using:35_con37.htm"; 
MM.HELP_cmdASPNetAddParam = "DW_Using:35_con38.htm"; 
MM.HELP_cmdPHPAddParam = "DW_Using:35_con39.htm"; 
MM.HELP_ssJSPRequestVariable = "DW_Using:35_con40.htm"; 
MM.HELP_ssCFSessionVariable = "DW_Using:35_con41.htm"; 
MM.HELP_ssSessionVariable = "DW_Using:35_con41.htm"; 
MM.HELP_ssApplicationVariable = "DW_Using:35_con42.htm"; 
MM.HELP_ssCFApplicationVariable = "DW_Using:35_con42.htm"; 
MM.HELP_ssCFURLVariable = "DW_Using:35_con43.htm"; 
MM.HELP_ssCFFormVariable = "DW_Using:35_con44.htm"; 
MM.HELP_ssCFClientVariable = "DW_Using:35_con45.htm"; 
MM.HELP_ssCFCookieVariable = "DW_Using:35_con46.htm"; 
MM.HELP_ssCFCGIVariable = "DW_Using:35_con47.htm"; 
MM.HELP_ssCFServerVariable = "DW_Using:35_con48.htm"; 
MM.HELP_ssCFVariablesVariable = "DW_Using:35_con49.htm"; 
MM.HELP_inspRecordset = "DW_Using:36_add15.htm"; 
MM.HELP_inspStoredProcedure = "DW_Using:36_add16.htm"; 
MM.HELP_inspJspPrepared = "DW_Using:36_add17.htm"; 
MM.HELP_inspRepeatedRegion = "DW_Using:36_add18.htm"; 
MM.HELP_ssHideRegion = "DW_Using:37_dis17.htm"; // various Show Region SBs
MM.HELP_objDynamicTable = "DW_Using:37_dis19.htm"; 
MM.HELP_sbRSStatsFirst = "DW_Using:37_dis22.htm"; // Display Starting Record Number 
MM.HELP_sbRSStatsLast = "DW_Using:37_dis22.htm"; // Display Ending Record Number 
MM.HELP_sbRSStatsTotal = "DW_Using:37_dis22.htm"; // Display Total Records 
MM.HELP_objRecordsetNavigation = "DW_Using:37_dis24.htm"; 
MM.HELP_ssMoveTo = "DW_Using:37_dis25.htm"; 
MM.HELP_ssRepeatedRegion = "DW_Using:37_dis26.htm"; 
MM.HELP_objRecordsetStatistics = "DW_Using:37_dis27.htm"; 
MM.HELP_fmt_ASP_Currency = "DW_Using:37_dis29.htm"; 
MM.HELP_fmt_JSP_Currency = "DW_Using:37_dis29.htm"; 
MM.HELP_fmt_JSP_Number = "DW_Using:37_dis29.htm"; 
MM.HELP_fmt_ASP_Number = "DW_Using:37_dis29.htm"; 
MM.HELP_fmt_ASP_Percent = "DW_Using:37_dis29.htm"; 
MM.HELP_fmt_JSP_Percent = "DW_Using:37_dis29.htm"; 
MM.HELP_ssRSStatsCurrentPage = "DW_Using:37_dis30.htm"; // Display Current Page Number
MM.HELP_ConfigureXSLTransform = "DW_Using:38_xml15.htm"; 
MM.HELP_cmdXSLTAddParam = "DW_Using:38_xml18.htm"; 
MM.HELP_objXSLTComment = "DW_Using:38_xml21.htm"; // Comment dialog
MM.HELP_cmdAttachXSLT = "DW_Using:38_xml30.htm"; // Attach XSLT Stylesheet
MM.HELP_objXSLTIf = "DW_Using:38_xml33.htm"; // XSL Conditional Region dialog
MM.HELP_objXSLTChoose = "DW_Using:38_xml34.htm"; // XSL Multiple Condition dialog
MM.HELP_inspXSLForEach = "DW_Using:38_xml35.htm"; // XSL Repeat Region PI
MM.HELP_inspXSLIf = "DW_Using:38_xml36.htm"; // XSL Conditional Region PI
MM.HELP_inspXSLChoose = "DW_Using:38_xml37.htm"; // XSL Multiple Condition PI
MM.HELP_cmdDeclMissingEntities = "DW_Using:38_xml38.htm"; // Missing Entity message box
MM.HELP_compWebServices = "DW_Using:39_usi10.htm"; 
MM.HELP_wsDefaultProxyGen = "DW_Using:39_usi16.htm"; 
MM.HELP_ssServerModelList = "DW_Using:39_usi17.htm"; 
MM.HELP_wsCF6ProxyGen = "DW_Using:39_usi19.htm"; // ColdFusion 6 Proxy Generator (JavaScript) 
MM.HELP_ssProxyChooser = "DW_Using:39_usi20.htm"; 
MM.HELP_wsProxyGenUsingIntrospector = "DW_Using:39_usi20.htm"; 
MM.HELP_objFormAccessOptions = "DW_Using:41_for37.htm"; //form objects accessibility dialog
MM.HELP_RadioGroup = "DW_Using:41_for38.htm"; 
MM.HELP_ssDynamicRadioGroupCF = "DW_Using:41_for39.htm"; // Dynamic Radio Group (ColdFusion)
MM.HELP_ssDynamicRadioGroupASPNet = "DW_Using:41_for39.htm"; // Dynamic Radio Group (ASP.NET)
MM.HELP_ssDynamicRadioGroup = "DW_Using:41_for40.htm"; // Dynamic Radio Group dialog box
MM.HELP_ssDynamicTextField = "DW_Using:41_for41.htm"; 
MM.HELP_ssDynamicCheckBox = "DW_Using:41_for42.htm"; 
MM.HELP_ssDynamicSelectList = "DW_Using:41_for43.htm"; 
MM.HELP_settingCFformProperties_PI = "DW_Using:42_rad80.htm"; 
MM.HELP_settingCFtextfieldProperties_PI = "DW_Using:42_rad81.htm"; 
MM.HELP_settingCFhiddenfieldProperties_PI = "DW_Using:42_rad82.htm"; 
MM.HELP_settingCFtextareaProperties_PI = "DW_Using:42_rad83.htm"; 
MM.HELP_settingCFbuttonProperties_PI = "DW_Using:42_rad84.htm"; 
MM.HELP_settingCFcheckboxProperties_PI = "DW_Using:42_rad85.htm"; 
MM.HELP_settingCFradiobuttonProperties_PI = "DW_Using:42_rad86.htm"; 
MM.HELP_settingCFselectProperties_PI = "DW_Using:42_rad87.htm"; 
MM.HELP_settingCFimagefieldProperties_PI = "DW_Using:42_rad88.htm"; 
MM.HELP_settingCFfilefieldProperties_PI = "DW_Using:42_rad89.htm"; 
MM.HELP_settingCFdatefieldProperties_PI = "DW_Using:42_rad90.htm"; 
MM.HELP_objMasterDetail = "DW_Using:42_rad91.htm"; 
MM.HELP_cmdCFAddColumn = "DW_Using:42_rad91.htm"; 
MM.HELP_objInsertRecord = "DW_Using:42_rad92.htm"; 
MM.HELP_soASPNetInsertForm = "DW_Using:42_rad92.htm"; 
MM.HELP_soFormFieldProps = "DW_Using:42_rad93.htm"; 
MM.HELP_ssInsertRecord = "DW_Using:42_rad94.htm"; 
MM.HELP_sbPHPInsertRecord = "DW_Using:42_rad95.htm"; // insert record PHP
MM.HELP_sbCFInsertRecord = "DW_Using:42_rad96.htm"; // insert record coldfusion
MM.HELP_sbASPNetInsertRecord = "DW_Using:42_rad97.htm"; 
MM.HELP_objUpdateRecord = "DW_Using:42_rad98.htm"; 
MM.HELP_sbCFUpdateRecord = "DW_Using:42_rad99.htm"; // update record coldfusion
MM.HELP_sbCFDeleteRecord = "DW_Using:42_ra100.htm"; // delete record coldfusion
MM.HELP_ssCFStoredProc = "DW_Using:42_ra101.htm"; // coldfusion mx stored procedure
MM.HELP_cmdCFAddStoredProcVar = "DW_Using:42_ra102.htm"; // add/edit stored procedure variable
MM.HELP_sbCheckNewUsername = "DW_Using:42_ra103.htm"; 
MM.HELP_sbLoginUser = "DW_Using:42_ra104.htm"; 
MM.HELP_sbRestrictAccessToPage = "DW_Using:42_ra105.htm"; 
MM.HELP_sbDefineAccessLevels = "DW_Using:42_ra106.htm"; 
MM.HELP_sbLogoutUser = "DW_Using:42_ra107.htm"; 
MM.HELP_CFLoginWizard_cmd = "DW_Using:42_ra108.htm"; 
MM.HELP_cmdCreateComponent = "DW_Using:42_ra109.htm"; 
MM.HELP_compCFCs = "DW_Using:42_ra110.htm"; // CFC view of Components panel
MM.HELP_CFCQuery_cmd = "DW_Using:42_ra111.htm"; 
MM.HELP_newCFC = "DW_Using:42_ra112.htm"; 
MM.HELP_editParam_cmd = "DW_Using:42_ra113.htm"; 
MM.HELP_objASPNETButton = "DW_Using:43_rad41.htm"; 
MM.HELP_objASPNETCheckBox = "DW_Using:43_rad42.htm"; 
MM.HELP_objASPNETImageButton = "DW_Using:43_rad43.htm"; 
MM.HELP_objASPNETLabel = "DW_Using:43_rad44.htm"; 
MM.HELP_objASPNETRadioButton = "DW_Using:43_rad45.htm"; 
MM.HELP_objASPNETTextBox = "DW_Using:43_rad46.htm"; 
MM.HELP_objASPNETCheckBoxList = "DW_Using:43_rad47.htm"; 
MM.HELP_objASPNETDropDownList = "DW_Using:43_rad48.htm"; 
MM.HELP_objASPNETListBox = "DW_Using:43_rad49.htm"; 
MM.HELP_objASPNETRadioButtonList = "DW_Using:43_rad50.htm"; 
MM.HELP_piASPNETButton = "DW_Using:43_rad51.htm"; 
MM.HELP_piASPNETCheckBox = "DW_Using:43_rad52.htm"; 
MM.HELP_piASPNETImageButton = "DW_Using:43_rad53.htm"; 
MM.HELP_piASPNETLabel = "DW_Using:43_rad54.htm"; 
MM.HELP_piASPNETRadioButton = "DW_Using:43_rad55.htm"; 
MM.HELP_piASPNETTextBox = "DW_Using:43_rad56.htm"; 
MM.HELP_piASPNETCheckBoxList = "DW_Using:43_rad57.htm"; 
MM.HELP_piASPNETDropDownList = "DW_Using:43_rad58.htm"; 
MM.HELP_piASPNETListBox = "DW_Using:43_rad59.htm"; 
MM.HELP_piASPNETRadioButtonList = "DW_Using:43_rad60.htm"; 
MM.HELP_soMenuProps = "DW_Using:43_rad61.htm"; 
MM.HELP_ssDataGridAspNet = "DW_Using:43_rad62.htm"; 
MM.HELP_sbASPNetDataGridBound = "DW_Using:43_rad63.htm"; 
MM.HELP_sbASPNetDataGridTemplate = "DW_Using:43_rad64.htm"; 
MM.HELP_sbASPNetDataGridHyperlink = "DW_Using:43_rad65.htm"; 
MM.HELP_sbASPNetDataGridEdit = "DW_Using:43_rad66.htm"; 
MM.HELP_sbASPNetDataGridDelete = "DW_Using:43_rad67.htm"; 
MM.HELP_ssDataListAspNet = "DW_Using:43_rad68.htm"; 
MM.HELP_ssAddDataFieldDlgAspNet = "DW_Using:43_rad69.htm"; 
MM.HELP_piDataGridAspNet = "DW_Using:43_rad70.htm"; 
MM.HELP_piDataListAspNet = "DW_Using:43_rad71.htm"; 
MM.HELP_soASPNetUpdateForm = "DW_Using:43_rad72.htm"; 
MM.HELP_sbASPNetUpdateRecord = "DW_Using:43_rad73.htm"; 
MM.HELP_sbASPNetDeleteRecord = "DW_Using:43_rad74.htm"; 
MM.HELP_sbASPNetStoredProc = "DW_Using:43_rad75.htm"; 
MM.HELP_cmdASPNetSprocParam = "DW_Using:43_rad76.htm"; 
MM.HELP_cmdASPNetBuildRuntime = "DW_Using:43_rad77.htm"; 
MM.HELP_ssGoToDetailPage = "DW_Using:44_rad32.htm"; 
MM.HELP_ssMoveToSpecificRecord = "DW_Using:44_rad33.htm"; 
MM.HELP_ssGoToRelatedPage = "DW_Using:44_rad34.htm"; 
MM.HELP_ssUpdateRecord = "DW_Using:44_rad35.htm"; 
MM.HELP_ssDeleteRecord = "DW_Using:44_rad36.htm"; 
MM.HELP_ssCommandAsp = "DW_Using:44_rad37.htm"; 
MM.HELP_ssCallableJsp = "DW_Using:44_rad38.htm"; 
MM.HELP_ssPreparedJsp = "DW_Using:44_rad39.htm"; 
MM.HELP_ssJavaBean = "DW_Using:44_rad40.htm"; 
MM.HELP_ssJavaBeanIndexed = "DW_Using:44_rad41.htm"; 
MM.HELP_sbPHPUpdateRecord = "DW_Using:45_rad26.htm"; // update record PHP
MM.HELP_sbPHPDeleteRecord = "DW_Using:45_rad27.htm"; // delete record PHP

